### ISSUE TITLE
Review/revision of the topical 'layers' of the CI

### ISSUE THREAD

**Issue by stuartasutton** [ld4pe/cieb#2]
The WordPress technical team is in need of a complete draft of the topical levels of the CI. The current CI structure is as follows:

-Topical Cluster
---Topic
------Competency
---------Benchmark

I've incuded here in github a SKOS representation of the topical levels as they currently stand in a very drafty, **very incomplete form**. 

The top two levels serve a 'contextualizing' function in the CI itself and also as a general technical mechanisms in Wordpress for general catorigation of learning resource.  _In a way, it is the table of contents for the learning resources_. While there is an expectation that the Competency and the Benchmark layers will evolve, _we hope that the topical levels can be as complete as possible as soon as possible_. That's a task of the EB.

There is a bit of urgency to the topical levels because the hundreds of learning resources already gathered and provided with descriptive metadata could be madde readily available now by being mapped to the topics...even though mapping the Competency and Benchmark levels can be done in a slightly more casual pace.

Stuart

[1] https://github.com/stuartasutton/cieb/blob/master/TopicIndex/LD4PE-TopicVocab.ttl
[2] https://github.com/stuartasutton/cieb/blob/master/TopicIndex/LD4PE-TopicVocab.rdf

**Comment by tombaker** [comment]
This has been resolved.
